version: '3.1'
services:
  db:
    image: postgres:latest
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=stc-assessment
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
    ports:
      - '5432:5432'
      - '8090:8080'
    hostname: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s

  assessment-app:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy


